/**
 * @description       : 
 * @author            : Subramani Kumarasamy
 * @group             : 
 * @last modified on  : 10-13-2023
 * @last modified by  : Subramani Kumarasamy
**/
public class AirlineWrapper {

    public Integer id;
    public String name;
    public String country;
    public String logo;
    public String slogan;
    public String head_quaters;
    public String website;
    public String established;
    
}