/**
 * @description       : 
 * @author            : Subramani Kumarasamy
 * @group             : 
 * @last modified on  : 10-16-2023
 * @last modified by  : Subramani Kumarasamy
**/
public class ObjectResponse {

    public String id;	//ff8081818b1b4123018b39c8653727b4
	public String name;	//Macbook Pro 16
	public String createdAt;	//2023-10-16T18:38:36.343+00:00
	public DataWrapper data;

	public class DataWrapper {
		public Integer year;	//2023
		public Double price;	//1600
		public String Hard_disk_size;	//1 TB SSD
		public String CPU_model;	//M2 Chip
	}
}