/**
 * @description       : 
 * @author            : Subramani Kumarasamy
 * @group             : 
 * @last modified on  : 10-16-2023
 * @last modified by  : Subramani Kumarasamy
**/
public class ObjectRequest {

    public String name;	//Apple MacBook Pro 16
	public DataWrapper data;

	public class DataWrapper {
		public Integer year;	//2019
		public Double price;	//1849.99
		public String CPU_model;	//Intel Core i9
		public String Hard_disk_size;	//1 TB
	}

}